[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/alok8663/Machine-Learning/blob/main/Data_Preprocessing/Data_Preprocessing.ipynb)


In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
data=pd.read_csv('Data.csv')

In [27]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [28]:
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [29]:
print(data.isnull().sum())

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


In [30]:
#use sk learn to fill missing values
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit_transform(X[:,1:3])
# X[:,1:3]=imputer.transform(X[:,1:3])



array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [31]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [32]:
#we need to convert categorical columns into  numerical columns
# if more than 2 values, use column transformer, if 2 values use label encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
col=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
ft=col.fit_transform(X)
X=np.array(ft)

In [33]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [34]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
y=label.fit_transform(y)

In [35]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [36]:
#now split data into two parts, i.e. 80% train, 20% testing
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [37]:
# standardisation baaad me krte h to avoid data leakage(taaki training aur test alag a;ag rhe, test set training se influence na ho, aur unseen test set pe kaam kr paye hmara model)
#scale data, so that all values lie in about same range, two types- 1.standardisation and normalisation
#after standardisation all values range-(-3,3),use mean and sd and normalisation se (0,1),use max min
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
# not fit here because mean and sd same rhe dono train aur test k liye
X_test=sc.transform(X_test)




In [38]:
print(X_train)
print(X_test)

[[-1.          2.64575131 -0.77459667  0.25315802         nan]
 [ 1.         -0.37796447 -0.77459667 -0.23014365  0.44897083]
 [-1.         -0.37796447  1.29099445 -1.84114924 -1.41706417]
 [-1.         -0.37796447  1.29099445         nan -1.0242147 ]
 [ 1.         -0.37796447 -0.77459667  1.54196248  1.62751925]
 [-1.         -0.37796447  1.29099445 -0.0690431  -0.14030338]
 [ 1.         -0.37796447 -0.77459667  0.89756025  0.94003267]
 [ 1.         -0.37796447 -0.77459667 -0.55234477 -0.43494049]]
[[-1.          2.64575131 -0.77459667 -1.35784756 -0.82778996]
 [-1.          2.64575131 -0.77459667  1.8641636   2.02036872]]
